all:
	gcc mai.c def.c -o r
	gcc pg.c def.c -o p
	gcc evp.c def.c -o m
	gcc prpre.c def.c -o b 
	gcc prpost.c def.c -o c 
	gcc bals.c def.c -o bals
clear:
	rm -rf r 
	rm -rf p 
	rm -rf m
	rm -rf a
	rm -rf b
	rm -rf c
	rm -rf aa
	rm -rf aaa 
